### PR TITLE
Fix GitHub Workflow Mac build, finally

### PR DESCRIPTION
**Pull request by tuffnatty**
OK I finally found out that I can trigger Actions, although only from the master branch, on my fork. This one has built succesfully.

### CODE REVIEW

**Comment by pawelsalawa** [comment]
Sorry I did not mention earlier how to run actions. I'm not sure which action have you executed, but be aware that the default build on master (after git push) is done under Linux.

The MacOS build is triggered only at 3AM during night and also per HTTP request (requires security token).

You can modify `macos_workflow.yml` workflow file on your branch to have it running after each push, see the `tests.yml` and its `on` directive at the beginning.

But that's only if you would need it ever again.

I'll merge this now and see how that goes (I'll trigger manually to see earlier).

**Comment by tuffnatty** [comment]
A Mac build have built OK at my repo: https://github.com/tuffnatty/sqlitestudio/actions/runs/1726811838

**Comment by pawelsalawa** [comment]
It did so too in here. Great, thanks!

**Comment by pawelsalawa** [comment]
Btw. are you able to use installer from produced packages under your Mac? You can see them in your action build at the bottom.

**Comment by tuffnatty** [comment]
@pawelsalawa Good catch! Both packages install and run OK, however, they can't load the ScriptingTcl plugin, probably because the Tcl library is built under MacOS 11, and I have Mac OS X 10.14 here:
```
[13:24:47] Cannot load plugin ScriptingTcl. Error details: Cannot load library /private/var/folders/_7/ldyd9nmd2njb3tcmwr3hn9p40000gn/T/AppTranslocation/3EA0E320-486A-4E9F-8539-8DF1CA428522/d/SQLiteStudio.app/Contents/PlugIns/libScriptingTcl.dylib: (dlopen(/private/var/folders/_7/ldyd9nmd2njb3tcmwr3hn9p40000gn/T/AppTranslocation/3EA0E320-486A-4E9F-8539-8DF1CA428522/d/SQLiteStudio.app/Contents/PlugIns/libScriptingTcl.dylib, 10): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /private/var/folders/_7/ldyd9nmd2njb3tcmwr3hn9p40000gn/T/AppTranslocation/3EA0E320-486A-4E9F-8539-8DF1CA428522/d/SQLiteStudio.app/Contents/PlugIns/../Frameworks/libtcl8.6.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /private/var/folders/_7/ldyd9nmd2njb3tcmwr3hn9p40000gn/T/AppTranslocation/3EA0E320-486A-4E9F-8539-8DF1CA428522/d/SQLiteStudio.app/Contents/PlugIns/../Frameworks/libtcl8.6.dylib)
```
However, this is better than before, when Tcl scripts did not work at all.

**Comment by pawelsalawa** [comment]
Hm. Shall we change the `runs-on: macos-latest` to `runs-on: macos-11` then? According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources the `latest` means `10.15`.

I wonder - if whole application is built on 11, would it work on 10.x?

**Comment by tuffnatty** [comment]
The build log says OS version is 11.6.2, so the documentation is probably outdated. However, I have not encountered any other errors with this build.
I would rather change to `runs-on: macos-10.15` so that more versions will be supported.
I tried this change on my fork, and the resulting build seems to work fine (Tcl as well) on my 10.14.

**Comment by pawelsalawa** [comment]
Interesting. I've updated the workflow file to use 10.15. Thanks!

**Pull request merged**
