### PR TITLE
Adds filtering to View data grid

### LINKED ISSUE #3195: Support filtering in View data grid
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3346
Originally created at: Fri Aug 18 01:47:20 2017
Originally last updated at: Fri Aug 18 01:47:20 2017

Filtering is currently supported for Table data grid, where one can filter by text, sql, etc. It would be good if filtering can be supported for View data grid too.\n\n**Operating system:**\nWindows (other)

### PR DESCRIPTION
**Pull request by electrickite**
This PR adds filtering to the View data grid/browser. It essentially duplicates the supporting functions in the datagrid table model. After testing, this approach appears to work for general filtering and column filtering - it returns correct results using string, regex, and SQL.

Resolves #3195

### CODE REVIEW

**Comment by pawelsalawa** [comment]
Thanks. It looks okay, though I will keep it open just for sake of refactoring when I sit down to this, because I'd prefer to avoid copy-pasted code is possible. I will move common parts in to shared base class.

**Comment by electrickite** [comment]
Makes sense. Would you rather see the shared code moved into `SqlQueryModel` or into a new base class for the table and view models?

**Comment by pawelsalawa** [comment]
I think this deserves an intermediate class, because `SqlQueryModel` is also used in `SqlEditor` and there it doesn't make sense to have these methods.
I think that ideally the hierarchy would be something l ike:
```
SqlQueryModel
    ^
    |
SqlDataSourceQueryModel
    ^           ^
    |           |
SqlTableModel  SqlViewModel
```

**Comment by electrickite** [comment]
@pawelsalawa Sounds reasonable. Pushed a new commit that creates a `SqlDataSourceQueryModel` class to hold the filtering logic.

**Comment by electrickite** [comment]
The latest update adds support for filtering views that use aliased columns in their query (using SQL `AS` column names).

**Comment by pawelsalawa** [comment]
Loos great. Thanks for the contribution!

**Pull request merged**
