### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by pawelsalawa**

### CODE REVIEW

**Comment by nikitaivantsov** [comment]
Good day.
After making my commit with the added/updated translations, I discovered, that the old version of Qt Linguist I use for translation is silently changing current TS version="2.1" tag back to TS version="2.0" on file save for an unknown reason. 
So I assume that CrowdIn now treats them as an old version files and wants to "upgrade" them (actually removing the changes/additions I made).
Could you please exclude all the *ru_RU.ts files from this pull request? I will change the versions to 2.2 and make another commit.

**Comment by pawelsalawa** [comment]
I don't think that ts version is the reason. This pull request does not modify TS version in the Russian translation file. It just changes indentation in all these files, but no translation is removed, nor version changed.

How do you commit/push your translations? Where?

**Comment by nikitaivantsov** [comment]
> How do you commit/push your translations? Where?

I commit modified *ru_RU.ts files directly to this repository through TortoiseGit, because you granted me this permission when moved to github (you sent me an invitation on 12.03.2018 to do so) as I've been translating SQLiteStudio to Russian for a long time.

> It just changes indentation in all these files, but no translation is removed, nor version changed.

Unfortunately, no. CrowdIn replaces them with the version it has, without translation I made, see for example DbAndroid_ru_RU.ts https://github.com/pawelsalawa/sqlitestudio/pull/4122/files#diff-bfe62179cf81c171edd8a40f5425ccff06cf947fdd60037aaf691b4b2227f3d3

**Comment by pawelsalawa** [comment]
I forgot ;) That's good.
Back to the topic - I don't think this pull request is discarding any of your changes. Among ru_RU files there is only one listed - 
 CsvImport. The changes to be merged are just indentation shifts (just like with all the rest files).

Am I missing something?

**Comment by nikitaivantsov** [comment]
> Am I missing something?

This page shows only first 250 commits, actual number of files changed = 292, including all RU files I modified as well (I also made a minor typo fix in CsvImport too, btw), you can see them in Files changed -> Jump to -> type ru_RU in filter field
I'm not sure if it looks for "ts version" specifically, but it's the first reasonable explanation I thought of.
Maybe CrowndIn will always replace them with the version it has, so to keep my translations they need to be uploaded to CrowdIn as well each time after I make my commits, but in that case I don't know yet how to do it (and will it be ok in your opinion).

**Comment by pawelsalawa** [comment]
You're right. I've reviewed it in GitHub Desktop and there I clearly see it. I will hold with this PR for now.

I'm not sure how CrowdIn treats translations made in-place (in the repository). It may be just a timing issue (you pushed your changes around the same time when CrowdIn pushed its own and it may have missed your translations & just overwritten them), or it may be a general issue of CrowdIn "owning" translation files and always preferring its translations (in which case Qt Linguist would no longer be an option). I hope it's that first reason.
I have reached out to CrowdIn team to help me understand this and act accordingly. I'll get back to this here.

**Comment by pawelsalawa** [comment]
Btw. Nikita, have you been pushing any other translations recently? Were they respected by CrowdIn so far? Are you able to verify this?

**Comment by nikitaivantsov** [comment]
Last time I made a commit back in February and they seem to be respected by CrowdIn, but i'm not sure. I checked CsvImport_ru_RU.ts and the small change I made back then didn't disappear. I cannot check the big files as they're marked as totally changed in every commit (due to indentation changes) and finding what exactly was added/modified is impossible.
I will wait for the CrownId answer and then your decision on how to update translations in future.
If this is a one-time coincidence, then you can accept this pull request, I will copy current translated files on my computer and make a new commit with them after syncing.

**Comment by pawelsalawa** [comment]
@nikitaivantsov I've synced your translations with CrowdIn and it looks good to merge now.

This is unfortunately manual operation to be executed in CrowdIn whenever I decide that code base has more recent translations. This is how GitHub <-> CrowdIn integration works (I got response from them).

Ideally you should use CrowdIn platform to enter your translations (try it, it's really nice! You can sign up with GitHub account). This way it would be fully automatic.

Otherwise - if you stick to Qt Linquist and push directly into repo, you will need to ping me every time to make a sync with CrowdIn.

The disadventage of using CrowdIn is that all translations are ultimately committed "by me", because the integration channel is set up through my account. If that's and issue (which I'd understand), let me know and I will look for possible solutions.

**Comment by nikitaivantsov** [comment]
I'm totally OK with using CrowdIn from now on if that's the case.
The process should be as automatic as possible, and I don't mind at all to you being the author of all CrowdIn commits.
It's great that you were able to properly synchronize my current translations. When the need arises, I'll continue the work the way it's now intended, through CrowdIn.

**Pull request merged**
