### PR TITLE
Make ConfigDialog::createPluginsTypeItem() always succeed.

### PR DESCRIPTION
**Pull request by tuffnatty**
Probably it was in the original plan?

### CODE REVIEW

**Comment by pawelsalawa** [comment]
Yes, looks like the way to go. Did you try it in runtime? Does it behave as expected?

**Comment by tuffnatty** [comment]
@pawelsalawa It looks like it does, that is, it does add my plugin's type branch and does not add any extra.

**Comment by pawelsalawa** [comment]
What if you click on the branch node itself? Does show empty page, or it does not change current page, whatever it is, or perhaps it crashes?
I'm fine with either 1st or 2nd option, but if the 3rd happens (crash), we need to secure it. I'm just making sure we are covered.

**Comment by tuffnatty** [comment]
@pawelsalawa It does option 2, that is, the page does not change, only the tree view selection.

**Comment by tuffnatty** [comment]
@pawelsalawa P.S. Well, it actually produces a qWarning() in ConfigDialog::switchPage(), but does not crash. I am not sure this warning is needed. Should I remove it as well?

**Comment by pawelsalawa** [comment]
It's good enough to proceed. If you feel it's quick to address the warning, feel free to fix it in your next PR. Less warnings is always better.

Thanks a lot for the contribution!

**Pull request merged**
