### PR TITLE
Extension-based collations in the Collations editor

### PR DESCRIPTION
**Pull request by tuffnatty**
This adds support for extension-based collations to the Collations Editor. It allows for persistent ICU collations, a feature requested in #4974.

### CODE REVIEW

**Comment by pawelsalawa** [comment]
Clever approach ;) Few remarks from my side:
- Instead of relying on "hacky" language string, why not to add another field to `CollationManager::Collation`? It could be enum, since it's just an integer. I know it's a bit more work, cause it requires handling in `CollationManagerImpl::storeInConfig()` and `CollationManagerImpl::loadFromConfig()`, but it doesn't mess with the `lang`.
- Also such string (if we stick to using the `lang` string) would not be translatable.
- On UI I would suggest to make it more distinctive. Having it as one of languages can very easily mislead users. How about changing the `+` button on toolbar, so it allows to register extension-provided collations?
image
^^^ could be extended with dropdown like it is in Table Window for adding rows:
image
The dropdown would have just 1 entry ("Register extension-provided collation" ? maybe ChatGTP would offer better label...) and it would add new `Collation` object with the enum pre-set to the custom registration.
- When editing "custom registration" type of entry, the "Language" dropdown would be forced (and readonly) to `SQL` and the code field label would be updated accordingly (just like you already did in this PR).

What do you think about it?

**Comment by pawelsalawa** [comment]
ChatGTP provided few options, from which `Register extension collation` I like the most, but feel free to find better suited name.

**Comment by tuffnatty** [comment]
Well, I opted for a minimal invasive approach here. Had also considered a separate radio button group to switch the interface to "Custom registration" mode, then it's also logical to propagate the setting to the config model, then we'll probably need a settings database migration... you know how it goes. But probably the interface can be improved. Regarding the translation part: I think it can be easily added with the current approach.

**Comment by pawelsalawa** [comment]
I understand your reasons and in most cases I support the simplest possible approach (I like the KISS principle - "Keep It Simple, Stupid"), although in this case it may not pay off in a long term.
Migration is not necessary. The enum (if missing in the config so far) could be defaulted in `CollationManagerImpl::loadFromConfig()`. One more line to be added in `CollationManagerImpl::storeInConfig()`. No need for extensive changes in config-related code.

Regarding translation - I'm not so sure it would work out seamlessly. I mean you can change your app language. If you store language in English and change to German, the stored language would not match. I'm not 100% sure how that would behave, but this is just example of risky case from top of my head.

**Comment by tuffnatty** [comment]
Regarding translation - QComboBox items support userData, and allow to separate visible text from underlying values with minimal pain.
But O.K., I have updated the patch to make the UI more distinct.
Screenshot 2024-08-12 at 21 22 36
It's much more complicated now.

**Comment by pawelsalawa** [comment]
Looks good. Thanks for taking the effort!

**Comment by pawelsalawa** [comment]
Also cherry-picked to 3.4 branch.

**Comment by tuffnatty** [comment]
Thanks! It would be also good to update the documentation. It's a pity the wiki doesn't permit pull requests.

**Pull request merged**
